name: mkdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-material mkdocstrings-python pymdown-extensions markdown-katex
      - run: mkdocs gh-deploy --force --clean --verbose
